
- link:
    ~/.atom/config.cson:
        path: atom/config.cson
    ~/.atom/init.coffee:
        path: atom/init.coffee
    ~/.atom/keymap.cson:
        path: atom/keymap.cson
    ~/.atom/snippets.cson:
        path: atom/snippets.cson
    ~/.atom/styles.less:
        path: atom/styles.less
