- clean: ["~"]

- shell:
    - [mv ~/.bashrc ~/.bashrc_bckup 2> /dev/null, "Backing up existing .bashrc file"]

- link:
    ~/.bashrc:       shells/bash/bashrc
    ~/.inputrc:       shells/bash/inputrc
    # ~/.bash_aliases: shells/bash/aliases
    # ~/.bash_logout:  shells/bash/logout
    # ~/.bash_profile: shells/bash/profile
