- link:
    ~/.vim:   editors/vim
    ~/.vimrc: editors/vim/vimrc
    ~/.vim.bundles: editors/vim/vimrc.bundles

# - shell:
#     - [vim -c 'PluginInstall' +qall, Installing vim plugins]
# - shell:
#     - [vim +VundleClean +qall, Cleaning vim plugins]
#     - [vim +VundleInstall +qall, Installing vim plugins]
