- link:
    ~/.vim:   editors/vim
    ~/.vimrc: editors/vim/vimrc

# - shell:
#     - [vim -c 'PluginInstall' +qall, Installing vim plugins]
- shell:
    - [vim +VundleClean +qall, Cleaning vim plugins]
    - [vim -c 'VundleInstall' +qall, Installing vim plugins]
