- shell:
    - git submodule update --init --recursive src/zplug
    # - apt-get install -y zsh

- link:
    ~/.zshrc: shells/zsh/zshrc
    ~/.zsh : shells/zsh
    ~/.zplug: src/zplug

- shell:
    - chsh -s $(which zsh)
