export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/shells/zsh
# export BACKGROUND="dark"
# export THEME="one"

command_exists() {
    type "$1" > /dev/null 2>&1
}

# display how long all tasks over 10 seconds take
export REPORTTIME=10

# this sets the color for zsh default and will change to screen-256color if in tmux session
export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=xterm-256color

# define the code directory
# This is where my code exists and where I want the `c` autocomplete to work from exclusively
if [[ -d ~/code ]]; then
    export CODE_DIR=~/code
fi

# source all .zsh files inside of the zsh/ directory
for config ($ZSH/**/*.zsh) source $config

if [[ -a ~/.localrc ]]; then
    source ~/.localrc
fi


# initialize autocomplete
autoload -U compinit add-zsh-hook
compinit

for config ($ZSH/**/*completion.zsh) source $config

export EDITOR='nvim'
export GIT_EDITOR='nvim'

export PATH=/usr/local/bin:$PATH
export PATH=$HOME/local/bin:$PATH


export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

# add /usr/local/sbin
if [[ -d /usr/local/sbin ]]; then
    export PATH=/usr/local/sbin:$PATH
fi

# adding path directory for custom scripts
export PATH=$DOTFILES/bin:$PATH

# check for custom bin directory and add to path
if [[ -d ~/bin ]]; then
    export PATH=~/bin:$PATH
fi

# [ -z "$TMUX" ] && export TERM=xterm-256color-italic

# # install rbenv
# if command_exists rbenv; then
#     eval "$(rbenv init -)"
# fi
#
# if [[ -d ~/.rvm ]]; then
#     PATH=$HOME/.rvm/bin:$PATH # Add RVM to PATH for scripting
#     source ~/.rvm/scripts/rvm
# fi

# alias git to hub
if command_exists hub; then
    eval "$(hub alias -s)"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_DEFAULT_OPTS='--height 40% --reverse --border --inline-info'

# fpath=(~/.zsh $fpath)
#
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# settings FZF to have window height and go to bottom
export FZF_DEFAULT_OPTS='--height 40% --reverse --border'

# getting z to work
source ~/.zsh/z.sh

light(){
    export THEME="one"
    export BACKGROUND="light"
}

dark(){
    export THEME="one"
    export BACKGROUND="dark"
}

bg(){
    # init vim and run to make sure that the tmuxline is set
    [ -f ~/.vim/init.vim ] && vim +so ~/.vim/init.vim +qall
}
