set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/

source ~/.vim/plugins.vim

filetype plugin indent on


set t_Co=256              " enable 256-color mode.
syntax enable             " enable syntax highlighting (previously syntax on).
colorscheme desert        " set colorscheme
set laststatus=2          " last window always has a statusline
filetype indent on        " activates indenting for files

set nohlsearch            " Don't continue to highlight searched phrases.
set incsearch             " But do highlight as you type your search.
set ignorecase            " Make searches case-insensitive.


set autoindent            " auto-indent
set smartindent				    " smart indent; stop indent when closing brackets etc

set number                " show line numbers
set backspace=indent,eol,start
set ruler                 " Always show info along bottom.
set number					" display absolute number of current line
set relativenumber			" display relative line numbers
set cursorline				" highlight current line

" tab control
set smarttab              " use tabs at the start of a line, spaces elsewhere
set tabstop=4             " tab spacing
set softtabstop=4         " unify
set shiftwidth=4          " indent/outdent by 4 columns
set shiftround            " always indent/outdent to the nearest tabstop
set expandtab             " use spaces instead of tabs
set completeopt+=longest

" invisible characters
set list
set listchars=tab:→\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
set showbreak=↪

" encoding
set fileencoding=utf-8
" break at last word instead of last char
set linebreak


" code folding settings
set foldmethod=syntax		" fold based on indent
set foldnestmax=10			" deepest fold is 10 levels
set nofoldenable			" don't fold by default
set foldlevel=1

" extra settings
set ttyfast					" faster redrawing
set diffopt+=vertical
set laststatus=2			" show the status line all the time
set so=7					" set 7 lines to the cursors - when moving vertical
set wildmenu				" enhanced command line completion

" Search down into subfolders
" Provides tab-completion for all file-releated tasks
set path+=**
set hidden					" current buffer can be put into background
set showcmd					" show incomplete commands
set noshowmode				" don't show which mode disabled for PowerLine
set wildmode=list:longest	" complete files like a shell
set scrolloff=3				" lines of text around cursor
set shell=$SHELL
set cmdheight=1				" command bar height
set title					" set terminal title


set magic					" set magix on, for regex


set showmatch				" show matching braces
set mat=2					" how many tenths of a second to blink
set complete +=kspell		" autocomplete from the dictionary when spellchecking is enabled
set spelllang=de,en				" set spell langs"


" make comments and HTML attributes italic
highlight Comment cterm=italic
highlight htmlArg cterm=italic
